[package]
name = "lamellar"
version = "0.1.0"
authors = ["Ryan D Friese <ryan.friese@pnnl.gov>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.3"
futures = "0.1"
lazy_static = "1.3.0"
serde_closure = "0.1.5"
crossbeam = "0.7"
chashmap = "2.2.2"
rand = "0.7.0"
parking_lot = "0.9"
indexmap = "1.3"
core_affinity = "0.5.9"
rofisys = { path = "../rofi-sys" }


#features are strictly additive.... can't have mutual exclusitivity
[features]
WorkStealingSched = []
SocketsBackend = []
RofiBackend = []

default = ["WorkStealingSched","RofiBackend"]

[profile.release]
opt-level=3
lto=true
codegen-units=1
debug = true   




[lib]
name="lamellar"
path="src/lib.rs"


[[bin]]
name="test"
path="src/main.rs"
