[package]
name = "lamellar"
version = "0.2.2"
authors = ["Ryan D. Friese <ryan.friese@pnnl.gov>", " Mark V Raugas <mark.raugas@pnnl.gov>", "Roberto Gioiosa <roberto.gioiosa@pnnl.gov>"]
edition = "2018"
description = "Lamellar is an asynchronous tasking runtime for HPC systems developed in RUST."
readme = "README.md"
repository = "https://github.com/pnnl/lamellar-runtime"
homepage = "https://github.com/pnnl/lamellar-runtime"
license-file = "LICENSE"
keywords = ["hpc","runtime","pgas","distributed","asynchronous"]
categories = ["asynchronous","concurrency", "network-programming","science"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2"
#futures = "0.1"
lazy_static = "1.3.0"
crossbeam = "0.7"
chashmap = "2.2.2"
rand = "0.7.3"
parking_lot = "0.9"
indexmap = "1.3"
core_affinity = "0.5.9"
rofisys = { version ="0.1.1", optional = true  }
log = "0.4"
simple_logger = "1.6.0"
lamellar-impl = { version = "=0.2.2", path = "impl" }
proc-macro-hack = "0.5"
inventory = "0.1"
serde_closure = { version = "0.1.5", optional = true }
hostname = "0.3"
rayon = "1.1"

[workspace]
members = ["impl"]



#features are strictly additive.... can't have mutual exclusitivity
[features]
nightly=["serde_closure"]
stable=[]
enable-rofi=["rofisys"]
enable-local=[]
default=[]


[profile.release]
opt-level=3
lto=true
codegen-units=1
debug = true   




[lib]
name="lamellar"
path="src/lib.rs"


[[bin]]
name="test"
path="src/main.rs"

[[example]]
name="am_closures_bw"
path="examples/am_closures_bw.rs"
required-features = ["nightly"]
